### ISSUE TITLE
Bug: SImple Typos on APETAX linker

### ISSUE THREAD

**Issue by Ceazor** [TBouder/RarityExtended#14]
### What happened 🆘
Simple Typo. 

I HAVE A FRIEND, THE WIFE OF THE UNCLE OF ONE OF MY COUSIN (ON MY MOTHER'S SIDE), THAT HAS REALLY GOOD PLAN. THE CURRENT APY IS 3.68%. DO YOU WANT TO APE-IN 

Change to 
I HAVE A FRIEND, THE WIFE OF THE UNCLE OF ONE OF MY COUSINS (ON MY MOTHER'S SIDE), THAT HAS A REALLY GOOD PLAN. THE CURRENT APY IS 3.68%. DO YOU WANT TO APE-IN 

### To Reproduce 🔂
https://rarity-git-feature-dungeon1-tbouder.vercel.app/tavern?tab=ftm-vault

### More 🔎
- Browser : 
- FTM Provider : 
- Adventurer ID :

**Comment by TBouder** [comment]
Corrected in the PR #11 ! Thank you !
