### ISSUE TITLE
Wallet disconnects from time to time

### ISSUE THREAD

**Issue by fameal** [TBouder/RarityExtended#19]
This is an example of the error when it happens. Reload and it works again, reconnecting the wallet.

![IMAGE 2021-09-10 21:44:54](https://user-images.githubusercontent.com/839844/132908994-859ff29c-26c6-4788-ad27-b029d37eabe0.jpg)

**Comment by TBouder** [comment]
Linked to [this issue](https://github.com/NoahZinsmeister/web3-react/issues/78).
I think I have a workaround, I will update that while fixing the #6
