### ISSUE TITLE
Bug: fetch ftmscan failed because of missing api key

### ISSUE THREAD

**Issue by ykou** [TBouder/RarityExtended#30]
### What happened 🆘
**A clear and concise description of what the bug is.**
If you refresh the home page https://rarityextended.com/ several times, you'll notice it does not show the existing summoner, instead, the page shows the UI for creating a summoner. 

This is due to the api requests sent to the ftmscan.com did not include a valid API key. 

![image](https://user-images.githubusercontent.com/5376112/133002855-584c31db-f6a7-4136-ae8a-73eee5595db0.png)

This caused the ftmscan to return an error message instead of the real data: 

![image](https://user-images.githubusercontent.com/5376112/133002879-09358f09-1c67-41f1-ab27-ac2ab360451d.png)

And the UI logic `updateRarities` always assumed the data is there. 

![Screen Shot 2021-09-12 at 1 45 21 PM](https://user-images.githubusercontent.com/5376112/133002890-40ff6ca5-620b-4264-b18e-c7660515110a.png)

### To Reproduce 🔂
Steps to reproduce the behavior: Refresh https://rarityextended.com/ a few times quickly. 

### Recommended fix

Please register an account on ftmscan to get an API key and embed the API key when deploying the web app. 

### More 🔎
- Browser : 
- FTM Provider : 
- Adventurer ID :

**Comment by TBouder** [comment]
Thank you for this bug report !
This is now fixed !

Thank you!
